/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace PharmaTree {
  export type UnitStruct = {
    parentId: BigNumberish;
    rootId: BigNumberish;
    level: BigNumberish;
    manufacturer: AddressLike;
    currentOwner: AddressLike;
    pendingReceiver: AddressLike;
    status: BigNumberish;
    quantity: BigNumberish;
    metadata: string;
  };

  export type UnitStructOutput = [
    parentId: bigint,
    rootId: bigint,
    level: bigint,
    manufacturer: string,
    currentOwner: string,
    pendingReceiver: string,
    status: bigint,
    quantity: bigint,
    metadata: string
  ] & {
    parentId: bigint;
    rootId: bigint;
    level: bigint;
    manufacturer: string;
    currentOwner: string;
    pendingReceiver: string;
    status: bigint;
    quantity: bigint;
    metadata: string;
  };
}

export interface PharmaTreeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "DEFAULT_ADMIN_ROLE"
      | "HANDLER_ROLE"
      | "MANUFACTURER_ROLE"
      | "acceptTransfer"
      | "addHandler"
      | "addManufacturer"
      | "admin"
      | "children"
      | "createChildUnits"
      | "createRootUnit"
      | "getChildren"
      | "getRoleAdmin"
      | "getUnitDetails"
      | "grantRole"
      | "hasRole"
      | "initiateTransfer"
      | "isHandler"
      | "isManufacturer"
      | "markAsSold"
      | "rejectTransfer"
      | "removeHandler"
      | "removeManufacturer"
      | "renounceRole"
      | "revokeRole"
      | "supportsInterface"
      | "unitCounter"
      | "units"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TransferCompleted"
      | "TransferInitiated"
      | "TransferRejected"
      | "UnitCreated"
      | "UnitSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "HANDLER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "MANUFACTURER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "acceptTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addHandler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "children",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createChildUnits",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createRootUnit",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getChildren",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnitDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isHandler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsSold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "rejectTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeHandler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unitCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "units", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "HANDLER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "MANUFACTURER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "acceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addHandler", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "children", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createChildUnits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRootUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChildren",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnitDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isHandler", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markAsSold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rejectTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeHandler",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unitCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "units", data: BytesLike): Result;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferCompletedEvent {
  export type InputTuple = [
    id: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [id: bigint, from: string, to: string];
  export interface OutputObject {
    id: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [id: bigint, from: string, to: string];
  export interface OutputObject {
    id: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferRejectedEvent {
  export type InputTuple = [
    id: BigNumberish,
    from: AddressLike,
    rejectedBy: AddressLike
  ];
  export type OutputTuple = [id: bigint, from: string, rejectedBy: string];
  export interface OutputObject {
    id: bigint;
    from: string;
    rejectedBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnitCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    parentId: BigNumberish,
    level: BigNumberish,
    owner: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    parentId: bigint,
    level: bigint,
    owner: string
  ];
  export interface OutputObject {
    id: bigint;
    parentId: bigint;
    level: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnitSoldEvent {
  export type InputTuple = [id: BigNumberish, soldBy: AddressLike];
  export type OutputTuple = [id: bigint, soldBy: string];
  export interface OutputObject {
    id: bigint;
    soldBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PharmaTree extends BaseContract {
  connect(runner?: ContractRunner | null): PharmaTree;
  waitForDeployment(): Promise<this>;

  interface: PharmaTreeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  HANDLER_ROLE: TypedContractMethod<[], [string], "view">;

  MANUFACTURER_ROLE: TypedContractMethod<[], [string], "view">;

  acceptTransfer: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  addHandler: TypedContractMethod<
    [_handler: AddressLike],
    [void],
    "nonpayable"
  >;

  addManufacturer: TypedContractMethod<
    [_mfr: AddressLike],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  children: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  createChildUnits: TypedContractMethod<
    [
      _parentId: BigNumberish,
      _childLevel: BigNumberish,
      _metadata: string,
      _count: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  createRootUnit: TypedContractMethod<
    [_level: BigNumberish, _metadata: string],
    [bigint],
    "nonpayable"
  >;

  getChildren: TypedContractMethod<
    [_parentId: BigNumberish],
    [bigint[]],
    "view"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  getUnitDetails: TypedContractMethod<
    [_id: BigNumberish],
    [PharmaTree.UnitStructOutput],
    "view"
  >;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  initiateTransfer: TypedContractMethod<
    [_id: BigNumberish, _receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  isHandler: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isManufacturer: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  markAsSold: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  rejectTransfer: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeHandler: TypedContractMethod<
    [_handler: AddressLike],
    [void],
    "nonpayable"
  >;

  removeManufacturer: TypedContractMethod<
    [_mfr: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  unitCounter: TypedContractMethod<[], [bigint], "view">;

  units: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string
      ] & {
        parentId: bigint;
        rootId: bigint;
        level: bigint;
        manufacturer: string;
        currentOwner: string;
        pendingReceiver: string;
        status: bigint;
        quantity: bigint;
        metadata: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "HANDLER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "MANUFACTURER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "acceptTransfer"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addHandler"
  ): TypedContractMethod<[_handler: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addManufacturer"
  ): TypedContractMethod<[_mfr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "children"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "createChildUnits"
  ): TypedContractMethod<
    [
      _parentId: BigNumberish,
      _childLevel: BigNumberish,
      _metadata: string,
      _count: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createRootUnit"
  ): TypedContractMethod<
    [_level: BigNumberish, _metadata: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getChildren"
  ): TypedContractMethod<[_parentId: BigNumberish], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "getUnitDetails"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [PharmaTree.UnitStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [_id: BigNumberish, _receiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isHandler"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isManufacturer"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markAsSold"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rejectTransfer"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeHandler"
  ): TypedContractMethod<[_handler: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "removeManufacturer"
  ): TypedContractMethod<[_mfr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, callerConfirmation: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "unitCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "units"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        bigint,
        bigint,
        string,
        string,
        string,
        bigint,
        bigint,
        string
      ] & {
        parentId: bigint;
        rootId: bigint;
        level: bigint;
        manufacturer: string;
        currentOwner: string;
        pendingReceiver: string;
        status: bigint;
        quantity: bigint;
        metadata: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TransferCompleted"
  ): TypedContractEvent<
    TransferCompletedEvent.InputTuple,
    TransferCompletedEvent.OutputTuple,
    TransferCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "TransferRejected"
  ): TypedContractEvent<
    TransferRejectedEvent.InputTuple,
    TransferRejectedEvent.OutputTuple,
    TransferRejectedEvent.OutputObject
  >;
  getEvent(
    key: "UnitCreated"
  ): TypedContractEvent<
    UnitCreatedEvent.InputTuple,
    UnitCreatedEvent.OutputTuple,
    UnitCreatedEvent.OutputObject
  >;
  getEvent(
    key: "UnitSold"
  ): TypedContractEvent<
    UnitSoldEvent.InputTuple,
    UnitSoldEvent.OutputTuple,
    UnitSoldEvent.OutputObject
  >;

  filters: {
    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TransferCompleted(uint256,address,address)": TypedContractEvent<
      TransferCompletedEvent.InputTuple,
      TransferCompletedEvent.OutputTuple,
      TransferCompletedEvent.OutputObject
    >;
    TransferCompleted: TypedContractEvent<
      TransferCompletedEvent.InputTuple,
      TransferCompletedEvent.OutputTuple,
      TransferCompletedEvent.OutputObject
    >;

    "TransferInitiated(uint256,address,address)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;

    "TransferRejected(uint256,address,address)": TypedContractEvent<
      TransferRejectedEvent.InputTuple,
      TransferRejectedEvent.OutputTuple,
      TransferRejectedEvent.OutputObject
    >;
    TransferRejected: TypedContractEvent<
      TransferRejectedEvent.InputTuple,
      TransferRejectedEvent.OutputTuple,
      TransferRejectedEvent.OutputObject
    >;

    "UnitCreated(uint256,uint256,uint8,address)": TypedContractEvent<
      UnitCreatedEvent.InputTuple,
      UnitCreatedEvent.OutputTuple,
      UnitCreatedEvent.OutputObject
    >;
    UnitCreated: TypedContractEvent<
      UnitCreatedEvent.InputTuple,
      UnitCreatedEvent.OutputTuple,
      UnitCreatedEvent.OutputObject
    >;

    "UnitSold(uint256,address)": TypedContractEvent<
      UnitSoldEvent.InputTuple,
      UnitSoldEvent.OutputTuple,
      UnitSoldEvent.OutputObject
    >;
    UnitSold: TypedContractEvent<
      UnitSoldEvent.InputTuple,
      UnitSoldEvent.OutputTuple,
      UnitSoldEvent.OutputObject
    >;
  };
}
