/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace PharmaTree {
  export type UnitStruct = {
    parentId: BigNumberish;
    level: BigNumberish;
    manufacturer: AddressLike;
    currentOwner: AddressLike;
    pendingReceiver: AddressLike;
    status: BigNumberish;
    metadata: string;
  };

  export type UnitStructOutput = [
    parentId: bigint,
    level: bigint,
    manufacturer: string,
    currentOwner: string,
    pendingReceiver: string,
    status: bigint,
    metadata: string
  ] & {
    parentId: bigint;
    level: bigint;
    manufacturer: string;
    currentOwner: string;
    pendingReceiver: string;
    status: bigint;
    metadata: string;
  };
}

export interface PharmaTreeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptTransfer"
      | "addHandler"
      | "addManufacturer"
      | "admin"
      | "createChildUnits"
      | "createRootUnit"
      | "getUnitDetails"
      | "initiateTransfer"
      | "isHandler"
      | "isManufacturer"
      | "markAsSold"
      | "unitCounter"
      | "units"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "TransferCompleted"
      | "TransferInitiated"
      | "UnitCreated"
      | "UnitSold"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptTransfer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "addHandler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "addManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "createChildUnits",
    values: [BigNumberish, BigNumberish, string, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "createRootUnit",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getUnitDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "initiateTransfer",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isHandler",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isManufacturer",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "markAsSold",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unitCounter",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "units", values: [BigNumberish]): string;

  decodeFunctionResult(
    functionFragment: "acceptTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "addHandler", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "addManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "createChildUnits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createRootUnit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getUnitDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initiateTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isHandler", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isManufacturer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "markAsSold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "unitCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "units", data: BytesLike): Result;
}

export namespace TransferCompletedEvent {
  export type InputTuple = [
    id: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [id: bigint, from: string, to: string];
  export interface OutputObject {
    id: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferInitiatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    from: AddressLike,
    to: AddressLike
  ];
  export type OutputTuple = [id: bigint, from: string, to: string];
  export interface OutputObject {
    id: bigint;
    from: string;
    to: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnitCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    parentId: BigNumberish,
    level: BigNumberish,
    owner: AddressLike
  ];
  export type OutputTuple = [
    id: bigint,
    parentId: bigint,
    level: bigint,
    owner: string
  ];
  export interface OutputObject {
    id: bigint;
    parentId: bigint;
    level: bigint;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnitSoldEvent {
  export type InputTuple = [id: BigNumberish, soldBy: AddressLike];
  export type OutputTuple = [id: bigint, soldBy: string];
  export interface OutputObject {
    id: bigint;
    soldBy: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface PharmaTree extends BaseContract {
  connect(runner?: ContractRunner | null): PharmaTree;
  waitForDeployment(): Promise<this>;

  interface: PharmaTreeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptTransfer: TypedContractMethod<
    [_id: BigNumberish],
    [void],
    "nonpayable"
  >;

  addHandler: TypedContractMethod<
    [_handler: AddressLike],
    [void],
    "nonpayable"
  >;

  addManufacturer: TypedContractMethod<
    [_mfr: AddressLike],
    [void],
    "nonpayable"
  >;

  admin: TypedContractMethod<[], [string], "view">;

  createChildUnits: TypedContractMethod<
    [
      _parentId: BigNumberish,
      _childLevel: BigNumberish,
      _metadata: string,
      _count: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  createRootUnit: TypedContractMethod<
    [_level: BigNumberish, _metadata: string],
    [bigint],
    "nonpayable"
  >;

  getUnitDetails: TypedContractMethod<
    [_id: BigNumberish],
    [PharmaTree.UnitStructOutput],
    "view"
  >;

  initiateTransfer: TypedContractMethod<
    [_id: BigNumberish, _receiver: AddressLike],
    [void],
    "nonpayable"
  >;

  isHandler: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  isManufacturer: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  markAsSold: TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;

  unitCounter: TypedContractMethod<[], [bigint], "view">;

  units: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint, string] & {
        parentId: bigint;
        level: bigint;
        manufacturer: string;
        currentOwner: string;
        pendingReceiver: string;
        status: bigint;
        metadata: string;
      }
    ],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptTransfer"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addHandler"
  ): TypedContractMethod<[_handler: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "addManufacturer"
  ): TypedContractMethod<[_mfr: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "createChildUnits"
  ): TypedContractMethod<
    [
      _parentId: BigNumberish,
      _childLevel: BigNumberish,
      _metadata: string,
      _count: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createRootUnit"
  ): TypedContractMethod<
    [_level: BigNumberish, _metadata: string],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getUnitDetails"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [PharmaTree.UnitStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "initiateTransfer"
  ): TypedContractMethod<
    [_id: BigNumberish, _receiver: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "isHandler"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isManufacturer"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "markAsSold"
  ): TypedContractMethod<[_id: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unitCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "units"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, string, string, string, bigint, string] & {
        parentId: bigint;
        level: bigint;
        manufacturer: string;
        currentOwner: string;
        pendingReceiver: string;
        status: bigint;
        metadata: string;
      }
    ],
    "view"
  >;

  getEvent(
    key: "TransferCompleted"
  ): TypedContractEvent<
    TransferCompletedEvent.InputTuple,
    TransferCompletedEvent.OutputTuple,
    TransferCompletedEvent.OutputObject
  >;
  getEvent(
    key: "TransferInitiated"
  ): TypedContractEvent<
    TransferInitiatedEvent.InputTuple,
    TransferInitiatedEvent.OutputTuple,
    TransferInitiatedEvent.OutputObject
  >;
  getEvent(
    key: "UnitCreated"
  ): TypedContractEvent<
    UnitCreatedEvent.InputTuple,
    UnitCreatedEvent.OutputTuple,
    UnitCreatedEvent.OutputObject
  >;
  getEvent(
    key: "UnitSold"
  ): TypedContractEvent<
    UnitSoldEvent.InputTuple,
    UnitSoldEvent.OutputTuple,
    UnitSoldEvent.OutputObject
  >;

  filters: {
    "TransferCompleted(uint256,address,address)": TypedContractEvent<
      TransferCompletedEvent.InputTuple,
      TransferCompletedEvent.OutputTuple,
      TransferCompletedEvent.OutputObject
    >;
    TransferCompleted: TypedContractEvent<
      TransferCompletedEvent.InputTuple,
      TransferCompletedEvent.OutputTuple,
      TransferCompletedEvent.OutputObject
    >;

    "TransferInitiated(uint256,address,address)": TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;
    TransferInitiated: TypedContractEvent<
      TransferInitiatedEvent.InputTuple,
      TransferInitiatedEvent.OutputTuple,
      TransferInitiatedEvent.OutputObject
    >;

    "UnitCreated(uint256,uint256,uint8,address)": TypedContractEvent<
      UnitCreatedEvent.InputTuple,
      UnitCreatedEvent.OutputTuple,
      UnitCreatedEvent.OutputObject
    >;
    UnitCreated: TypedContractEvent<
      UnitCreatedEvent.InputTuple,
      UnitCreatedEvent.OutputTuple,
      UnitCreatedEvent.OutputObject
    >;

    "UnitSold(uint256,address)": TypedContractEvent<
      UnitSoldEvent.InputTuple,
      UnitSoldEvent.OutputTuple,
      UnitSoldEvent.OutputObject
    >;
    UnitSold: TypedContractEvent<
      UnitSoldEvent.InputTuple,
      UnitSoldEvent.OutputTuple,
      UnitSoldEvent.OutputObject
    >;
  };
}
